
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "mysql:root:root@tcp(127.0.0.1:3306)/user_db?loc=Local&parseTime=true"
        tables: "user,enterprise"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true