// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"user/internal/dao/internal"
)

// internalEnterpriseDao is internal type for wrapping internal DAO implements.
type internalEnterpriseDao = *internal.EnterpriseDao

// enterpriseDao is the data access object for table enterprise.
// You can define custom methods on it to extend its functionality as you wish.
type enterpriseDao struct {
	internalEnterpriseDao
}

var (
	// Enterprise is globally public accessible object for table enterprise operations.
	Enterprise = enterpriseDao{
		internal.NewEnterpriseDao(),
	}
)

// Fill with you ideas below.
